module.exports = [
    "Limsa Lominsa",
    "Middle La Noscea",
    "Lower La Noscea",
    "Eastern La Noscea",
    "Western La Noscea",
    "Upper La Noscea",
    "Outer La Noscea",
    "Wolves' Den Pier",
    "Mist",
    "Gridania",
    "Central Shroud",
    "East Shroud",
    "South Shroud",
    "North Shroud",
    "The Lavender Beds",
    "Ul'dah",
    "Western Thanalan",
    "Central Thanalan",
    "Eastern Thanalan",
    "Southern Thanalan",
    "Northern Thanalan",
    "The Goblet",
    "Ishgard",
    "Coerthas Central Highlands",
    "Coerthas Western Highlands",
    "The Sea of Clouds",
    "Azys Lla",
    "Idyllshire",
    "The Dravanian Forelands",
    "The Dravanian Hinterlands",
    "The Churning Mists",
    "Rhalgr's Reach",
    "The Fringes",
    "The Peaks",
    "The Lochs",
    "Kugane",
    "Shirogane",
    "The Ruby Sea",
    "Yanxia",
    "The Azim Steppe",
    "Mor Dhona",
    "Eureka Anemos",
    "Eureka Pagos",
    "Eureka Hydatos",
    "The Crystarium",
    "Eulmore",
    "Lakeland",
    "Kholusia",
    "Amh Araeng",
    "Il Mheg",
    "The Rak'tika Greatwood",
    "The Tempest"
];
